--- #YAML:1.0
name:               CGI-Test
version:            0.2.4
abstract:           CGI regression test framework
author:
    - Raphael Manfredi <Raphael_Manfredi@pobox.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:                0
    Digest::MD5:        0
    File::Spec:         0
    File::Temp:         0
    Getargs::Long:      0.103
    HTML::TreeBuilder:  0
    HTTP::Message:      0
    Log::Agent:         0.207
    Storable:           1.000
    URI:                1.10
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=CGI-Test
    repository:  http://github.com/nohuhu/CGI-Test
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
