---
abstract: 'CGI regression test framework'
author:
  - 'Raphael Manfredi <Raphael_Manfredi@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Test
no_index:
  directory:
    - t
    - inc
requires:
  CGI: 0
  Digest::MD5: 0
  File::Spec: 0
  File::Temp: 0
  HTML::TreeBuilder: 0
  HTTP::Message: 0
  Storable: 1.000
  URI: 1.10
resources:
  bugtracker: http://github.com/nohuhu/CGI-Test/issues
  repository: http://github.com/nohuhu/CGI-Test
version: 0.31
